# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0009_auto_20170511_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholariumprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
