# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0016_auto_20180507_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholariumprofile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
